# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('email_id', models.EmailField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
