# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(2017, 7, 22)),
        ),
    ]
