# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170722_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(2017, 7, 31)),
        ),
    ]
