# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170731_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodfacts',
            fields=[
                ('nbd_no', models.IntegerField(primary_key=True, serialize=False)),
                ('shrt_desc', models.CharField(max_length=500)),
                ('water_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('energy_kcal', models.DecimalField(decimal_places=3, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('lipid_tot_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ash_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('carbohydrate_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fiber_td_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('sugar_tot_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('calcium_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('iron_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('magnesium_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('phosphorus_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('potassium_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('sodium_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('zinc_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('copper_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('manganese_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('selenium_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_c_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('thiamin_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('riboflavin_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('niacin_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('panto_acid_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_b6_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('folate_tot_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('folic_acid_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('food_folate_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('folate_DFE_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('choline_tot_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_b12_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_a_iu', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_a_rae', models.DecimalField(decimal_places=3, max_digits=7)),
                ('retinol_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('alpha_carot_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('beta_carot_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('beta_crypt_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('lycopene_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('lut_zea_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_e_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_d_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_d_iu', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vit_k_ug', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fat_sat_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fat_mono_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fat_poly_g', models.DecimalField(decimal_places=3, max_digits=7)),
                ('cholestrol_mg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('gm_wt_1', models.DecimalField(decimal_places=3, max_digits=7)),
                ('gm_wt_desc1', models.CharField(max_length=100)),
                ('gm_wt_2', models.DecimalField(decimal_places=3, max_digits=7)),
                ('gm_wt_desc2', models.CharField(max_length=100)),
                ('refuse_pct', models.IntegerField()),
            ],
        ),
    ]
