# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_foodfacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodfacts',
            name='nbd_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
