# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170731_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('pub_date', models.DateField(default=datetime.date(2017, 8, 3))),
                ('breakfast', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True)),
                ('lunch', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True)),
                ('dinner', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(2017, 8, 3)),
        ),
    ]
