# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170803_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_diet',
            name='bf_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='dn_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='ln_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(2017, 8, 9)),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='pub_date',
            field=models.DateField(default=datetime.date(2017, 8, 9)),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
