# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170809_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_diet',
            name='bf_size',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='dn_size',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='ln_size',
        ),
    ]
