# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20170809_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_diet',
            name='entry_date',
            field=models.DateField(default=datetime.date(2017, 8, 9)),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='nbd_breakfast',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='nbd_dinner',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='nbd_lunch',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
