# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20170809_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_diet',
            old_name='nbd_breakfast',
            new_name='nbd_fooditem',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='nbd_dinner',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='nbd_lunch',
        ),
        migrations.RemoveField(
            model_name='user_diet',
            name='weight',
        ),
        migrations.AddField(
            model_name='user_diet',
            name='mealtype',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='user_diet',
            name='serve_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
