# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='entry_date',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
        migrations.AlterField(
            model_name='user_diet',
            name='pub_date',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
        migrations.AlterField(
            model_name='user_weight',
            name='entry_date',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
        migrations.AlterField(
            model_name='user_weight',
            name='pub_date',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
    ]
