# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20170811_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='media'),
        ),
    ]
